### PR TITLE
Good band, good band

### PR DESCRIPTION
**Pull request by smt**
You know you want it.

I omitted the following from the list, because the world would end if they were included:
- Band
- Can
- Live
- Love
- Nice
- The
- Them
- Who
- Yes

Also, snuck Panera in there next to Pantera.

### CODE REVIEW

**Comment by smt** [comment]
Some of these might not actually be bands. ¯\_(ツ)_/¯

**Comment by johnmichel** [comment]
LGTM.

I'll probably end up removing a few more too-common band names though.

**Comment by smt** [comment]
I think there are not too many that will be a problem, especially since there is a word-break on either side of the pattern ;)

**Pull request merged**
